### ISSUE TITLE
Skalierung bei niedrigen Auflösungen

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#1]
Bei niedrigen Auflösungen (z.B. 640x480) spinnt die Skalierung in Vollbild und Fenstermodus unterschiedlich.

Fenstermodus macht Probleme bei Text unter Piktogrammen:
![skalierung1](https://cloud.githubusercontent.com/assets/15103150/12716813/a15b9336-c8e3-11e5-91ed-5e828e00ce1d.png)

Vollbildmodus macht bereits im Hauptmenü Ärger:
![skalierung2](https://cloud.githubusercontent.com/assets/15103150/12716815/a6f832ea-c8e3-11e5-97c8-efda823a8ba0.png)

**Comment by yoktobit** [comment]
Ausprobiert, hab ich anscheinend schon gefixt
