### ISSUE TITLE
Zählergeschwindigkeit im Shop erhöhen

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#105]
Ich habe eben über 400 Kupfernuggets aufeinmal verkauft und musste eine Ewigkeit warten, bis der Maximalwert im Shop erreicht war im Dialog. Bitte den Zähler bei gedrückter Taste (hoch/runter) deutlich schneller machen, vielleicht gleich verdoppeln.

Die Vorstufe, also das langsame Zählen vorher, kann entfallen!

**Bitte so einrichten:
Bei gedrückter Taste wartet der Zähler eine Sekunde, danach rattert er in vollem Tempo los.**

**Comment by yoktobit** [comment]
wird nicht exakt wie gefordert, aber nach 2 sek ist es rasant und nach 4 wahnsinnige Geschwindigkeit
