### ISSUE TITLE
Moral ersetzt O2

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#11]
In tieferen Regionen der Unterwelt sollten der Schwierigkeitsgrad erhöht bzw. das zu schnelle Voranschreiten des Spielers dadurch beeinflusst werden, dass der Sauerstoff immer knapper wird. Das macht beim näheren Betrachten wenig Sinn. Daher soll die O2-Skala durch eine Moral-Skala ersetzt werden. Dazu ersetzen wir einfach die O2-Grafik im UI durch die Moral-Grafik. Abhängig von Ricos Gemütszustand ändert sich das Piktogramm vor der Skala. Miner Rico ist ein Teufelskerl, doch auch er kann sich schlecht fühlen.

[grafiken moral.zip](https://github.com/yoktobit/minerminingminesunity/files/173923/grafiken.moral.zip)

**Comment by yoktobit** [comment]
offen gelassen, Bilder wechseln noch nicht und in der Zuarbeit fehlt die Transparenz (tz)
