### ISSUE TITLE
Bildschirm folgt Rico bei Bewegung

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#123]
Bewegt sich Rico horizontal, folgt ihm das Bild wenige Pixel (ich denke 1-3px). Ganz am Anfang der Spielentwicklung hatten wir das so gewollt eingestellt, dann aber gänzlich deaktiviert.

Ich spiele auf Vollbild 1366x768px Win10.

**Comment by yoktobit** [comment]
Scheint ein Rundungsfehler zu sein wegen 16:9...vielleicht sollten wir wirklich das Spiel einfach skalieren, wie es die faulen Leute tun.
