### ISSUE TITLE
Fundstücke im Inventar anzeigen

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#27]
Alles, was der Rico findet, soll im Inventar angezeigt werden. Momentan findet er nur:

Kupfer
Silber
Gold
Platin
Gems

All diese Fundstücke sollen im Inventar angezeigt werden, Stackgröße pro Platz ist 99. Ist im Inventar nichts mehr frei, hebt Rico nichts mehr auf. Alle Fundstücke können auf Wunsch einzeln entsorgt werden.

**Comment by yoktobit** [comment]
Öhm, hatten wir nicht gesagt, dass die Fundstücke eben nicht im Inventar erscheinen sollen, sondern nur oben?
