### ISSUE TITLE
Lebenspunkte regenerieren

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#32]
Rico soll, wenn die Hungerskala im Bereich 80-100% liegt (er also keinen Hunger hat), ganz langsam Lebenspunkte regenerieren.

Wünschenswerter Zusatz:
Die Regeneration soll langsamer werden, umso mehr Lebenspunkte Rico hat. Ist er fast tot, regeneriert er schneller. Machbar?

**Comment by yoktobit** [comment]
Ich habs jetzt mal so eingebaut mit (3.0 - 1.0/33.0 \* Health) / 2
