### ISSUE TITLE
Aufheben von Fundstücken

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#5]
Betritt Miner Rico ein Feld, in dem sich Bodenchätze befinden, nimmt er sie auf. Dies soll bitte nur dann passieren, wenn Rico auf dem Feld stehen bleibt. Es soll möglich sein, ein Feld mit Bodenschätzen zu durchlaufen, ohne aufzuheben. Man muss also auch den Nachbarblock eines Feldes mit Bodenschätzen abbauen können.

**Comment by yoktobit** [comment]
Was passiert, wenn dann der Nachbarblock fertig abgebaut ist? Dann steht ja der Miner auf dem vorherigen Feld...soll er dann anfangen, aufzuheben? Wenn nicht, wie hebt man dann auf? Feld verlassen und neu betreten? Das wäre nicht sonderlich intuitiv. Brauchen wir vielleicht doch eine Taste zum Aufheben? Bzw. zusätzlich für Touchdevices ein anklickbares Symbol, was nur erscheint, wenn man auf einem Feld mit Fundstücken ist? Dann kann man selbst entscheiden, wann er sich bückt.

**Comment by ghost** [comment]
Erledigt sich durch Ticket [https://github.com/yoktobit/minerminingminesunity/issues/6](url)
