### ISSUE TITLE
Endscreen und UI Sprache

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#53]
Wir sollten vor dem Alpha-Release noch einige Texte übersetzen für die deutschen Spieler.

Der Endscreen sollte auf deutschen Systemen übersetzt werden.

Auch das UI (Day -> Tag, Spade -> Schaufel, Pick -> Hacke). Zu überlegen wäre hier auch, ob wir einem Teil aus dem Weg gehen wollen und einfach die Kästchen für Schaufel, Spitzhacke und Extra einfach größer machen, vertikal zentrieren und dafür den Text entfernen. Was meinst du?

Außerdem im Inventar USE DROP -> BEN WEG. Obwohl ich mir beim Inventar nicht sicher bin, ob USE und DROP nicht bleiben könnten.

**Comment by yoktobit** [comment]
Ein paar Texte sind schon übersetzt, aber das HUD noch nicht, da brauch ich erst noch eine Idee
