### ISSUE TITLE
Lichtverhältnisse neu einstellen

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#58]
Seit der neuen Version von Miner hat sich etwas an der Beleuchtung geändert. Die feinen Verläufe der Lichtkegel sind nun recht abrupt. Bekommen wir das wieder so hin, wie es vorher war?

**Comment by yoktobit** [comment]
Das ist so beabsichtigt, wenn die Grafikqualität auf "Fastest" eingestellt ist.
