### ISSUE TITLE
Aufheben Stück für Stück

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#6]
Ich stelle das mal als Frage.

Wäre es nicht sinnvoll, Rico die Fundstücke in einem Feld Stück für Stück aufheben zu lassen? Liegen beispielsweise 3 Kupferstücke in einem Feld, muss sich Rico 3x bücken. Oder er hebt 2 Fundstücke auf pro Aufhebeanimation?!

**Comment by yoktobit** [comment]
Bei vielen Fundstücken dauert das eine Weile...was passiert, wenn man in der Zwischenzeit etwas anderes tun möchte? Abbruch der Aufhebanimation?

**Comment by ghost** [comment]
Genau, wie man aktuell während des Betretens eines Feldes eine Richtungstaste drücken und somit die weitere Bewegungsrichtung von Miner Rico "planen" kann, sollen auf dem aktuellen Feld befindliche Fundstücke ignoriert werden. Man könnte einfach einen kurzen Counter einfügen, der beispielsweise nach 0,5s automatisch mit dem Aufheben beginnt. Drückt man während der Aufhebeanimation eine Richtungstaste, wird die aktuelle Animation beendet bzw. das aktuelle Fundstück aufgehoben und Rico bewegt sich danach weg vom Feld bzw. baut den Nachbarblock ab.

**Comment by yoktobit** [comment]
Kleiner Unterschied bei der aktuellen Implementierung: Jedes einzelne Bücken kann nicht abgebrochen werden...man sollte sich in der Nähe von Gegnern also überlegen, ob man den Miner die Seife aufheben lassen möchte.
