### ISSUE TITLE
Fensterwechsel im Vollbildmodus

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#7]
Wechselt man während des Spielens im Vollbildmodus mit Hilfe von Alt+Tab in ein anderes Fenster, kann man danach nicht wieder ins Spiel zurückkehren. Eben bin ich außerdem aus dem Spiel geflogen, weil Teamviewer eine Windows-Einblendung unten im Tray gezeigt hat. Auch danach war das Spielfenster nicht wieder aktivierbar.

Kann man da was machen? :-\

**Comment by yoktobit** [comment]
Scheint ein DX11-Problem von Unity zu sein
