### ISSUE TITLE
neue Grafiken für Rohstoffe im UI

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#70]
Bitte diese Grafiken zum Tausch der alten Grafiken im UI verwenden. Habe hier nur etwas gespiegelt und gedreht. So sieht nicht jeder Rohstoff exakt gleich aus.

![ui pic resources au](https://cloud.githubusercontent.com/assets/15103150/19105732/cec5cbee-8ae3-11e6-8c6f-688c715b9cfe.png)
![ui pic resources cu](https://cloud.githubusercontent.com/assets/15103150/19105733/cece8bbc-8ae3-11e6-8804-16e99d2f92f0.png)
![ui pic resources pt](https://cloud.githubusercontent.com/assets/15103150/19105734/cecf77f2-8ae3-11e6-959e-7a019044fdf2.png)
![ui pic resources ag](https://cloud.githubusercontent.com/assets/15103150/19105735/cecff222-8ae3-11e6-881d-143e23d67658.png)

**Comment by yoktobit** [comment]
Bitte nochmal per Mail schicken...die Grafiknamen werden von GitHub komplett entstellt und ob die pngs noch 100% Original sind, würde ich auch bezweifeln.
