### ISSUE TITLE
Animationen für Interaktionen

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#73]
Hier die Animationen für diverse Interaktionen. Jede Grafik misst 10x10 Pixel.

Enthaltene Animationen in der ZIP:
- Sprechblase (mit jemandem reden --> Ehefrau, Quests in Saloon)
- drehende Münze (Händlermenü im Shop öffnen)
- sich öffnende Tür (Gebäude betreten --> Saloon, Zuhause, Händler)

[grafiken für interaktionen.zip](https://github.com/yoktobit/minerminingminesunity/files/633489/grafiken.fur.interaktionen.zip)

**Comment by yoktobit** [comment]
schon länger drin
