### ISSUE TITLE
Korrekturen im Shop

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#74]
1. Tasteneingaben werden im Shop oft nicht angenommen, weder Enter noch Pfeiltasten (hoch, runter im VK- oder EK-Dialog); hat also nichts damit zu tun, dass der Dialog nicht im Vordergrund ist. Leider, und das macht mir die größten Sorgen, passiert das vor allem dann, wenn ich besonders **schnell** navigiere bzw. in sehr kurzer Abfolge Tasten nacheinander drücke.
2. Durch den Verkauf von Items frei gewordene Slots bleiben reserviert für Items der gleichen Art. Doof!
3. Alles, was ich an den Händler verkaufe und was er vorher nicht im Angebot hatte, kann ich für 0 Gold zurück kaufen.
4. Laden betreten und verlassen mit mit ENTER **und** Pfeiltaste ermöglichen; ebenso Aufrufen des Shops direkt vor Gerald
5. Featurewunsch: Schnelles Hoch- oder Runterzählen einer Menge X von Items durch Gedrückthalten der Cursortasten.

**Comment by ghost** [comment]
Damn: Dass schnelle Tastenfolgen nicht angenommen werden, gilt für das gesamte Spiel, beispielsweise auch fürs Ingame-Menü. Wenn ich hier sehr schnell navigiere, hat das Spielaussetzer von einer halben Sekunde.

**Comment by yoktobit** [comment]
Ähm...das sind 5 Bugs in einem...Bitte zwingend(!) nur einen Bug pro Issue! Habe jetzt 1. gefixt und bitte für die restlichen um separate Meldungen, sonst won't fix -> Erziehungsmaßnahme.
