### ISSUE TITLE
Gold wertvoller als Platin

### ISSUE THREAD

**Issue by ghost** [yoktobit/minerminingminesunity#99]
Schon doof - im Originalspiel MinerVGA aus den 80ern war Platin der wertvollste Bodenschatz und somit wertvoller als Gold. Offenbar hat sich das mittlerweile geändert. Gold ist heute wertvoller als Platin.

**Die Datenbank habe ich hinsichtlich Preisen und Fundgebieten angepasst. Müssen wir weitere Anpassungen machen?**

**Comment by yoktobit** [comment]
Ist schon lange so drin irgendwie, mmh....
